Microverse Student Portfolio(Works/about section)
tomdan-ai/My-Portfolio pull request #2
Opened 2023-02-17 11:11 UTC by tomdan-ai

### **Microverse Student Portfolio(Works/about section)**

- [ ] Added more images to the img folder
- [ ] Added a new section in HTML
- [ ] Added more styles

2023-02-17 11:51 UTC, frank1738 requested changes
Hi @tomdan-ai , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 11:51 UTC, frank1738 commented on index.html
> +                A daily selection of privately personalized reads; no accounts
- [ ] In your project cards, kindly position your elements correctly. Adjust the padding and spacing to match the original design

![image](https://user-images.githubusercontent.com/98453979/219640368-0b9b1b50-e71e-48fc-b4cd-594488e347f3.png)

### Checkout the original design

![image](https://user-images.githubusercontent.com/98453979/219640640-313f41fc-0a44-4a86-b6b7-8ad7d473ed24.png)

2023-02-17 11:51 UTC, frank1738 commented on index.html
> +        <div class="flex">
- [ ] Kindly ensure there is a spacing between the `headline section` and the `projects section` to match the original design

![image](https://user-images.githubusercontent.com/98453979/219641215-e14f2312-fd57-4dca-b324-e37251ecd1bc.png)

### Checkout the original design

![image](https://user-images.githubusercontent.com/98453979/219641455-c0dde6fe-5c68-4ed5-9e58-7ea38274bd17.png)

2023-02-17 11:51 UTC, frank1738 commented on index.html
> +        <div class="main-container">
- [ ] Kindly wrap your `about me content` in a `<section>` tag for semantic reasons.

2023-02-17 11:51 UTC, frank1738 commented on index.html
> +                    <a href="#">
- [ ] Kindly ensure there is a spacing between the `work section` and the `about me section` like in the Figma design
- [ ] Work on the positioning and spacing of elements in your `about me section` to match the original design.

![image](https://user-images.githubusercontent.com/98453979/219644287-fb840cff-d585-45b1-92c8-e022b2610014.png)

### Checkout the original design

![image](https://user-images.githubusercontent.com/98453979/219644746-0ef3de4c-a7ff-4ee5-94e0-fdb6fca1003c.png)

2023-02-17 11:51 UTC, frank1738 commented on index.html
> +                    <img src="img/IMG 5.png" alt="javascript logo">
- [ ] In your languages section, kindly ensure that the language logos are perfect circles to match the original design
- [ ] You can also reduce the padding in the `skills` and `frameworks` sections to match the original design

![image](https://user-images.githubusercontent.com/98453979/219645973-a445801f-23b7-4e26-aa4e-1d7cfe7490e3.png)

### Checkout the original design
![image](https://user-images.githubusercontent.com/98453979/219646080-5bee0e9c-5a8c-40f1-af4c-955857f5d525.png)

2023-02-17 22:31 UTC, MeqdamAlqudah requested changes
Hi @tomdan-ai , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![image](https://user-images.githubusercontent.com/74744787/219806669-0ff05c3b-954b-446c-9987-c7314d219645.png)


 ## Highlights
:+1: no linter errors 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 22:31 UTC, MeqdamAlqudah commented on index.html
> +        <div class="is-me flex column">
- [ ] Please as the last reviewer said Kindly ensure there is a spacing between the work section and the about me section like in the Figma design
![image](https://user-images.githubusercontent.com/74744787/219805163-6a61628f-6ea6-48f0-969f-a75b74138f2f.png)

2023-02-17 22:31 UTC, MeqdamAlqudah commented on index.html
> +          <h2 class="tonic-class">Tonic</h2>
- [ ] Please as the last reviewer said  Kindly ensure there is a spacing between the headline section and the projects section to match the original design 
![image](https://user-images.githubusercontent.com/74744787/219805299-c0dc612a-2059-4e11-8758-bffe9070e8f4.png)

2023-02-17 22:31 UTC, MeqdamAlqudah commented on index.html
> +          <h2 class="tonic-class">Tonic</h2>
- [Optional ] Please make sure that the last card in the work section has the card shape as in the design, and as other cards
![image](https://user-images.githubusercontent.com/74744787/219805577-408bf2a3-ea01-4331-b495-51997e6e1320.png)

2023-02-17 22:31 UTC, MeqdamAlqudah commented on index.html
> +          <div class="canopy">
- [ Optional] Please add some space to the left of the about me section to match the design
![image](https://user-images.githubusercontent.com/74744787/219805995-be9882db-6937-42da-95e3-513c8ccfd972.png)

2023-02-18 09:13 UTC, Abdessittir approved these changes
Hi  @tomdan-ai , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)


## Highlights
✅ Requested changes implemented
✅ Good commit messages
✅ Good design
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 09:23 UTC, merged